suppressMessages(library(forensim))
data(strusa)
cat("===== tabfreq (strusa) structure =====\n")
cat("class:", class(strusa), "\n"); cat("slotNames:", slotNames(strusa), "\n")
cat("\n@tab is a list; names (loci):\n"); print(head(names(strusa@tab)))
cat("\nstr of @tab[[1]] (first locus freqs):\n"); print(str(strusa@tab[[1]]))
cat("first locus freq head:\n"); print(head(strusa@tab[[1]]))
cat("\n@pop.names:\n"); print(strusa@pop.names)

cat("\n===== simumix structure =====\n")
gen <- simugeno(strusa, n=c(0,0,5))
mix4 <- simumix(gen, ncontri=c(0,0,4))
cat("class:", class(mix4), "\n"); cat("slotNames:", slotNames(mix4), "\n")
cat("\nstr of whole simumix:\n"); print(str(mix4))
cat("\n@mix.all (alleles per locus) head:\n"); print(head(mix4@mix.all, 3))

cat("\n===== as.tabfreq / as.simumix signatures =====\n")
print(args(as.tabfreq)); print(args(as.simumix))
cat("\n--- sanity: likestim + mincontri on the simulated 4-person mix ---\n")
print(likestim(mix4, strusa, refpop="Cauc"))
