suppressMessages(library(forensim))
data(strusa)
gen <- simugeno(strusa, n=c(0,0,5)); mix4 <- simumix(gen, ncontri=c(0,0,4))
cat("@ncontri:\n"); print(mix4@ncontri)
cat("@which.loc:\n"); print(mix4@which.loc)
cat("@mix.all (first 3 loci):\n"); print(mix4@mix.all[1:3])
cat("@mix.prof (first 3 loci):\n"); print(mix4@mix.prof[1:3])
cat("@popinfo:\n"); print(mix4@popinfo)
cat("\n=== as.simumix help/example ===\n")
db <- tools::Rd_db("forensim")
cat(paste(capture.output(tools::Rd2txt(db[["as.simumix.Rd"]])), collapse="\n"))
cat("\n\n=== as.tabfreq help/example ===\n")
cat(paste(capture.output(tools::Rd2txt(db[["as.tabfreq.Rd"]])), collapse="\n"))
